using System;
using System.Collections.Generic;
using UnityEngine;

namespace MidiGenPlay.Composition
{
    /// <summary>
    /// Authoring asset that selects the base melodic strategy and optional
    /// per-phrase directives (weighted) to modify/override the strategy
    /// for individual phrases (e.g., enforce ascent, repeat a motif).
    /// Used by MelodyTrackComposer when deciding which IMelodyStrategy
    /// to apply on each phrase generated by the PhrasePlanner.
    /// </summary>
    [CreateAssetMenu(menuName = "MidiGenPlay/Melody/MelodicStyle")]
    public class MelodicStyleSO : ScriptableObject
    {
        [Header("Base strategy for this track/pattern")]
        public MelodyStrategyId baseStrategy = MelodyStrategyId.ScaleFlow;

        [Header("Per-phrase (optional)")]
        public bool usePerPhraseOverrides = false;
        public List<WeightedPhraseDirective> perPhraseDirectives = new();

        [Range(0, 1)] public float swingAmount = 0f;   // reserved for later
        [Range(0, 1)] public float humanize = 0f;      // reserved for later
    }

    /// <summary>
    /// Constrains the melodic direction of a phrase.
    /// None = free movement, AscendingOnly = nudge upwards, DescendingOnly = nudge downwards.
    /// </summary>
    public enum ContourConstraint { None, AscendingOnly, DescendingOnly }

    /// <summary>
    /// Weighted directive applied to a single phrase: can override the base strategy,
    /// constrain contour, and optionally repeat/transposed motif notes.
    /// </summary>
    [Serializable]
    public class WeightedPhraseDirective
    {
        [Range(0f, 1f)] public float weight = 1f;

        [Tooltip("If null, the baseStrategy is used.")]
        public MelodyStrategyId? overrideStrategy = null;

        public ContourConstraint contour = ContourConstraint.None;

        [Tooltip("If set, repeat the last N notes (optionally transposed).")]
        public RepeatLastNotesDirective repeatDirective;
    }

    /// <summary>
    /// Repeats the most recent motif fragment and optionally transposes it.
    /// </summary>
    [Serializable]
    public class RepeatLastNotesDirective
    {
        [Range(1, 8)] public int notesToRepeat = 2;
        public int transposeSemitones = 0;
    }
}