using System;
using System.Collections.Generic;
using UnityEngine;

namespace MidiGenPlay.Composition
{
    /// <summary>
    /// Authoring asset that selects the base melodic strategy and optional
    /// per-phrase directives (weighted) to modify/override the strategy
    /// for individual phrases (e.g., enforce ascent, repeat a motif).
    /// Used by MelodyTrackComposer when deciding which IMelodyStrategy
    /// to apply on each phrase generated by the PhrasePlanner.
    /// </summary>
    [CreateAssetMenu(menuName = "MidiGenPlay/Melody/MelodicStyle")]
    public class MelodicStyleSO : ScriptableObject
    {
        [Header("Base strategy for this track/pattern")]
        public MelodyStrategyId baseStrategy = MelodyStrategyId.ScaleFlow;

        [Header("Per-phrase (optional)")]
        public bool usePerPhraseOverrides = false;
        public List<WeightedPhraseDirective> perPhraseDirectives = new();

        // MGP-MEL-1 P2.2: reserved -- NOT consumed by any composer yet.
        // Hidden so they cannot be authored into silence; unhide when the
        // MIDI-emission stage actually implements them.
        [HideInInspector][Range(0, 1)] public float swingAmount = 0f;
        [HideInInspector][Range(0, 1)] public float humanize = 0f;
    }

    [Serializable]
    public struct WeightedInt
    {
        public int value;               // e.g., 12 (octave) or 2 (two scale steps)
        [Range(0f, 1f)] public float weight;
    }

    public enum IntervalMode
    {
        FixedSemitones,            // legacy: semitonesPerPhrase
        PerDirectionSemitones,     // weighted semitone choices for Up/Down
        PerDirectionScaleSteps     // weighted SCALE-STEP choices for Up/Down
    }

    public enum RelativeMode
    {
        Anchor,        // offsets measured from the first anchor
        PreviousTarget // offsets applied from last output note (phrase-to-phrase walk)
    }

    public enum AnchorStartMode { AutoFromDirection, Lowest, Highest, Mid, Random }

    // where to take the pitch-class from when applying the interval
    public enum PitchClassSource
    {
        Anchor,         // use the very first anchor's pitch-class
        Candidate,      // use the strategy's candidate pitch-class (current default)
        ComputedRegister // take PC from baseNote+interval result (regNote)
    }

    [Serializable]
    public class InterPhraseIntervalDirective
    {
        [Tooltip("Enable phrase-to-phrase transposition pattern.")]
        public bool enabled = false;

        [Header("Pitch-class source")]
        [Tooltip("Which note provides the pitch-class when applying the interval")]
        public PitchClassSource pitchClassSource = PitchClassSource.Candidate;


        [Header("General")]

        public IntervalMode mode = IntervalMode.FixedSemitones;
        public RelativeMode relativeMode = RelativeMode.PreviousTarget;
        [Tooltip("Base direction: +1 = up, -1 = down.")]
        public int baseDirection = 1;
        [Tooltip("If true, flip direction every phrase: up/down/up/down...")]
        public bool alternateDirection = false;
        [Tooltip("Clamp to instrument range; if we hit the edge, stay on the boundary.")]
        public bool clampToRange = true;

        [Header("Anchor Behaviour")]
        [Tooltip("Where to set first note (anchor)")]
        public AnchorStartMode anchorStart = AnchorStartMode.AutoFromDirection;

        [Header("Fixed Semitones")]
        [Tooltip("Interval in semitones per phrase step. 12 = octave, 7 = fifth, 3 = minor third, etc.")]
        public int semitonesPerPhrase = 12;

        [Header("Weighted Choices")]
        // weighted choices per direction (semitones)
        public List<WeightedInt> upSemitones = new();
        public List<WeightedInt> downSemitones = new();
        // weighted choices per direction (scale steps)
        // (1 = next scale degree, 2 = skip one, etc.)
        public List<WeightedInt> upScaleSteps = new();
        public List<WeightedInt> downScaleSteps = new();

        // Whether to apply interval on the very first emitted note.
        // If false, the first note is output without transposition and the pattern starts on the next phrase.
        [Header("Lifecycle")]
        public bool applyOnFirstNote = false;

        // If applyOnFirstNote == false, choose what the first output note should use for pitch-class.
        // - true  -> use 'anchor' as first note (honors anchorStart: Lowest/Highest/Mid/...)
        // - false -> use the strategy 'candidate' as first note
        public bool firstNoteUsesAnchor = false;
    }

    /// <summary>
    /// Constrains the melodic direction of a phrase.
    /// None = free movement, AscendingOnly = nudge upwards, DescendingOnly = nudge downwards.
    /// </summary>
    public enum ContourConstraint { None, AscendingOnly, DescendingOnly }

    /// <summary>
    /// Weighted directive applied to a single phrase: can override the base strategy,
    /// constrain contour, and optionally repeat/transposed motif notes.
    /// </summary>
    [Serializable]
    public class WeightedPhraseDirective
    {
        [Range(0f, 1f)] public float weight = 1f;

        // MGP-MEL-1 P2.1: replaces the former `MelodyStrategyId?` field.
        // Unity does NOT serialize Nullable<T>, so the nullable could never
        // appear in the inspector nor carry a value -- live composer code fed
        // by a field that never persisted. No data migration needed for the
        // same reason (nothing was ever serialized).
        [Tooltip("Enable to override the base strategy for phrases that draw " +
                 "this directive.")]
        public bool useOverrideStrategy = false;

        [Tooltip("Strategy used when useOverrideStrategy is on.")]
        public MelodyStrategyId overrideStrategy = MelodyStrategyId.ScaleFlow;

        public ContourConstraint contour = ContourConstraint.None;

        [Tooltip("If set, repeat the last N notes (optionally transposed).")]
        public RepeatLastNotesDirective repeatDirective;

        [Tooltip("Optional inter-phrase transposition pattern.")]
        public InterPhraseIntervalDirective intervalDirective;
    }

    /// <summary>
    /// Repeats the most recent motif fragment and optionally transposes it.
    /// </summary>
    [Serializable]
    public class RepeatLastNotesDirective
    {
        public bool enabled = false;
        [Range(1, 8)] public int notesToRepeat = 2;

        /// <summary>
        /// MGP-TONALITY-1 D-TON6=A. How the per-cycle motif transpose is
        /// interpreted. ChromaticSemitones (0, serialized default) is the
        /// legacy behavior: raw semitones, may leave the scale (this was
        /// S1's root cause with transposeSemitones=2 on 'Showtime').
        /// ScaleDegrees moves the motif N SCALE DEGREES per cycle — the
        /// classic diatonic sequence — and can never leave the scale for
        /// motif notes that are in it. Existing assets serialize 0 and are
        /// byte-identical.
        /// </summary>
        public enum MotifTransposeMode
        {
            ChromaticSemitones = 0,
            ScaleDegrees = 1
        }

        public MotifTransposeMode transposeMode =
            MotifTransposeMode.ChromaticSemitones;

        [Tooltip("Per completed motif cycle. In ChromaticSemitones: raw " +
                 "semitones (+/-12 = octave; other values can leave the " +
                 "key). In ScaleDegrees: diatonic degrees (+1 = one scale " +
                 "step up per cycle). 0 = exact ostinato in both modes.")]
        public int transposeSemitones = 0;
    }
}