using System;
using System.Collections.Generic;
using UnityEngine;

namespace MidiGenPlay.Composition
{
    /// <summary>
    /// Authoring asset that selects the base melodic strategy and optional
    /// per-phrase directives (weighted) to modify/override the strategy
    /// for individual phrases (e.g., enforce ascent, repeat a motif).
    /// Used by MelodyTrackComposer when deciding which IMelodyStrategy
    /// to apply on each phrase generated by the PhrasePlanner.
    /// </summary>
    [CreateAssetMenu(menuName = "MidiGenPlay/Melody/MelodicStyle")]
    public class MelodicStyleSO : ScriptableObject
    {
        [Header("Base strategy for this track/pattern")]
        public MelodyStrategyId baseStrategy = MelodyStrategyId.ScaleFlow;

        [Header("Per-phrase (optional)")]
        public bool usePerPhraseOverrides = false;
        public List<WeightedPhraseDirective> perPhraseDirectives = new();

        [Range(0, 1)] public float swingAmount = 0f;   // reserved for later
        [Range(0, 1)] public float humanize = 0f;      // reserved for later
    }

    /// <summary>
    /// Constrains the melodic direction of a phrase.
    /// None = free movement, AscendingOnly = nudge upwards, DescendingOnly = nudge downwards.
    /// </summary>
    public enum ContourConstraint { None, AscendingOnly, DescendingOnly }

    public enum AnchorStartMode { AutoFromDirection, Lowest, Highest, Mid, Random }

    [Serializable]
    public class InterPhraseIntervalDirective
    {
        [Tooltip("Enable phrase-to-phrase transposition pattern.")]
        public bool enabled = false;

        [Tooltip("Interval in semitones per phrase step. 12 = octave, 7 = fifth, 3 = minor third, etc.")]
        public int semitonesPerPhrase = 12;

        [Tooltip("Base direction: +1 = up, -1 = down.")]
        public int baseDirection = 1;

        [Tooltip("If true, flip direction every phrase: up/down/up/down...")]
        public bool alternateDirection = false;

        [Tooltip("Clamp to instrument range; if we hit the edge, stay on the boundary.")]
        public bool clampToRange = true;

        [Tooltip("Where to set first note (anchor)")]
        public AnchorStartMode anchorStart = AnchorStartMode.AutoFromDirection;

        [Tooltip("If true, keep the anchor's pitch class and only change octave (C -> C -> C...). " +
             "If false, keep each candidate's pitch class and only change its octave.")]
        public bool lockPitchClassToAnchor = true;
    }

    /// <summary>
    /// Weighted directive applied to a single phrase: can override the base strategy,
    /// constrain contour, and optionally repeat/transposed motif notes.
    /// </summary>
    [Serializable]
    public class WeightedPhraseDirective
    {
        [Range(0f, 1f)] public float weight = 1f;

        [Tooltip("If null, the baseStrategy is used.")]
        public MelodyStrategyId? overrideStrategy = null;

        public ContourConstraint contour = ContourConstraint.None;

        [Tooltip("If set, repeat the last N notes (optionally transposed).")]
        public RepeatLastNotesDirective repeatDirective;

        [Tooltip("Optional inter-phrase transposition pattern.")]
        public InterPhraseIntervalDirective intervalDirective;
    }

    /// <summary>
    /// Repeats the most recent motif fragment and optionally transposes it.
    /// </summary>
    [Serializable]
    public class RepeatLastNotesDirective
    {
        public bool enabled = false;
        [Range(1, 8)] public int notesToRepeat = 2;
        public int transposeSemitones = 0;
    }
}